language: android

android:
  components:
  - tools
  - platform-tools
  - build-tools-23.0.1
  - android-23
  - extra-android-m2repository
  - extra-android-support

jdk:
  - oraclejdk7

sudo: false

script: 'travis_retry ./gradlew build --parallel'

cache:
  directories:
    - $HOME/.gradle/caches
