language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.1
    - android-23
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-android-support

  licenses:
    - 'android-sdk-license.*'

jdk:
  - openjdk7
  - oraclejdk7

sudo: false

notifications:
  email: false

cache:
  directories:
	- $HOME/.gradle/caches
